version: '2.13'

services:
    api:
      container_name: api
      build: .
      restart: always
      env_file:
        - .env
      volumes:
        - .:/usr/src/app
        - /usr/src/node_modules
      depends_on:
        - mongodb
        - postgres
      links:
        - mongodb
      ports:
        - 3001:3001
      command: npm run start

    mongodb:
      image: mongo:latest
      container_name: mongodb
      env_file:
        - .env
      volumes:
        - dbdata-volume:/data/mongodb
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}

    postgres:
      image: postgres
      restart: always
      env_file:
        - .env
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

volumes:
  dbdata-volume: